# database ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k9s101.p.ssafy.io:3306/cocotaxi
    username: root
    password: 1234

#    # SSAFY MariaDB
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P31S101?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: S09P31S101
#    password: vCLYNcqE0x

    # MySQL (비상용)
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cocotaxi?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 1234

  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9000
