# database ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    #??
    #    url: jdbc:mariadb://localhost:3305/cocotexi
    #    username: root
    #    password: 1234

    # SSAFY MariaDB
    url: jdbc:mariadb://k9s101.p.ssafy.io:3306/cocotaxi
    username: root
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8000
